// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1xLElAIOL6YTq0Xi--42KETbveV7jVE',
    appId: '1:1455783023:web:58f98e168fa0d2e507e19a',
    messagingSenderId: '1455783023',
    projectId: 'parkpaws-9a9b0',
    authDomain: 'parkpaws-9a9b0.firebaseapp.com',
    storageBucket: 'parkpaws-9a9b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm32sfrLOTWxGSViEGjQPQiRViqOai_Ws',
    appId: '1:1455783023:android:447050f08481d12807e19a',
    messagingSenderId: '1455783023',
    projectId: 'parkpaws-9a9b0',
    storageBucket: 'parkpaws-9a9b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOLD54gAyputAWon57drxUNm4te1ggArA',
    appId: '1:1455783023:ios:4d14a34dc63ba8e107e19a',
    messagingSenderId: '1455783023',
    projectId: 'parkpaws-9a9b0',
    storageBucket: 'parkpaws-9a9b0.appspot.com',
    iosClientId: '1455783023-ualh6faev4qei98c85eq6hjqdeknkaqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkpaws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOLD54gAyputAWon57drxUNm4te1ggArA',
    appId: '1:1455783023:ios:4d14a34dc63ba8e107e19a',
    messagingSenderId: '1455783023',
    projectId: 'parkpaws-9a9b0',
    storageBucket: 'parkpaws-9a9b0.appspot.com',
    iosClientId: '1455783023-ualh6faev4qei98c85eq6hjqdeknkaqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkpaws',
  );
}
